"""Document ingestion: extract text, chunk it, embed it, persist to ChromaDB.

Per project policy, `OllamaClient` is the only component allowed to talk to
Ollama over HTTP. Embeddings are therefore generated by calling
`OllamaClient.embed` directly (via a small LangChain-compatible adapter)
instead of using `langchain_ollama.OllamaEmbeddings`, which would open its
own HTTP connection outside that seam and be impossible to mock uniformly.
"""

import uuid
from pathlib import Path
from typing import Any

import chromadb
from chromadb.api.models.Collection import Collection
from docx import Document as DocxDocument
from langchain_text_splitters import RecursiveCharacterTextSplitter
from pypdf import PdfReader

from core.config import settings
from core.ollama_client import OllamaClient
from core import ollama_client as ollama_client_module

SUPPORTED_EXTENSIONS = {".pdf", ".docx", ".txt"}
COLLECTION_NAME = "documents"

# Deliberately separate from agents.tools.summarize: that one is prompted to
# produce a topic/bullet-structured answer (right for a chat-style agent
# response), while a document's post-indexing summary reads better as a
# short, flowing paragraph — not a list of headings and bullets.
_DOCUMENT_SUMMARY_PROMPT_TEMPLATE = (
    "Resuma o texto a seguir em português, em um único parágrafo corrido "
    "(sem títulos, sem tópicos, sem marcadores), destacando as partes mais "
    "importantes:\n\n{text}"
)


async def _generate_document_summary(text: str, ollama_client: OllamaClient) -> str:
    """Generate a short prose summary of `text` for the document listing."""
    prompt = _DOCUMENT_SUMMARY_PROMPT_TEMPLATE.format(text=text)
    tokens = [
        token
        async for token in ollama_client.chat([{"role": "user", "content": prompt}], stream=True)
    ]
    return "".join(tokens)


class UnsupportedFileTypeError(ValueError):
    """Raised when the uploaded file extension is not supported."""


class DocumentExtractionError(ValueError):
    """Raised when text could not be extracted from an otherwise supported file."""


def get_chroma_collection() -> Collection:
    """Return the (persisted) Chroma collection used to store document chunks.

    Explicitly uses cosine distance rather than Chroma's default (squared L2):
    embedding models like `nomic-embed-text` produce unnormalized vectors
    where L2 distances routinely run into the hundreds, which collapses
    `_distance_to_similarity`'s 0..1 output near zero and makes every result
    fail `rag_score_threshold` in practice. Cosine distance is scale-invariant
    and keeps scores meaningfully spread across 0..1 regardless of embedding
    magnitude.
    """
    chroma_client = chromadb.PersistentClient(path=settings.chroma_persist_dir)
    return chroma_client.get_or_create_collection(
        name=COLLECTION_NAME, metadata={"hnsw:space": "cosine"}
    )


def _extract_text(file_path: Path, extension: str) -> str:
    """Extract raw text from a document, dispatching on file extension."""
    if extension == ".pdf":
        try:
            reader = PdfReader(str(file_path))
            pages_text = [page.extract_text() or "" for page in reader.pages]
        except Exception as exc:  # noqa: BLE001 - normalize all extraction failures
            raise DocumentExtractionError(
                "Não foi possível extrair texto do documento"
            ) from exc
        text = "\n".join(pages_text).strip()
    elif extension == ".docx":
        try:
            docx_document = DocxDocument(str(file_path))
            text = "\n".join(paragraph.text for paragraph in docx_document.paragraphs).strip()
        except Exception as exc:  # noqa: BLE001 - normalize all extraction failures
            raise DocumentExtractionError(
                "Não foi possível extrair texto do documento"
            ) from exc
    else:  # .txt
        try:
            text = file_path.read_text(encoding="utf-8").strip()
        except (UnicodeDecodeError, OSError) as exc:
            raise DocumentExtractionError(
                "Não foi possível extrair texto do documento"
            ) from exc

    if not text:
        raise DocumentExtractionError("Não foi possível extrair texto do documento")

    return text


async def ingest_document(
    file_path: str,
    filename: str,
    ollama_client: OllamaClient | None = None,
) -> dict[str, Any]:
    """Ingest a single document: extract, chunk, embed, and persist it.

    Args:
        file_path: Path to the file on disk (already saved by the upload route).
        filename: Original filename, used for validation and metadata.
        ollama_client: Optional injected client (defaults to the shared singleton),
            primarily so tests can pass a mock.

    Returns:
        A dict shaped `{id, filename, chunks_count, status}`.

    Raises:
        UnsupportedFileTypeError: If the file extension is not one of
            `SUPPORTED_EXTENSIONS`.
        DocumentExtractionError: If no text could be extracted (corrupted file
            or empty content).
    """
    ollama = ollama_client or ollama_client_module.client
    path = Path(file_path)
    extension = Path(filename).suffix.lower()

    if extension not in SUPPORTED_EXTENSIONS:
        raise UnsupportedFileTypeError(
            f"Formato de arquivo não suportado: '{extension}'. "
            f"Formatos aceitos: {', '.join(sorted(SUPPORTED_EXTENSIONS))}"
        )

    text = _extract_text(path, extension)

    # Truncate before summarizing (not before chunking/embedding — the full
    # text is still indexed) so a large document can't blow past the local
    # model's context window; see settings.rag_summary_max_chars.
    summary = await _generate_document_summary(text[: settings.rag_summary_max_chars], ollama)

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=settings.rag_chunk_size,
        chunk_overlap=settings.rag_chunk_overlap,
    )
    chunks = splitter.split_text(text)

    document_id = str(uuid.uuid4())
    embeddings = [await ollama.embed(chunk) for chunk in chunks]
    ids = [f"{document_id}-{index}" for index in range(len(chunks))]
    metadatas = [
        {
            "filename": filename,
            "chunk_index": index,
            "document_id": document_id,
            "summary": summary,
        }
        for index in range(len(chunks))
    ]

    collection = get_chroma_collection()
    collection.add(
        ids=ids,
        embeddings=embeddings,
        documents=chunks,
        metadatas=metadatas,
    )

    return {
        "id": document_id,
        "filename": filename,
        "chunks_count": len(chunks),
        "status": "indexed",
        "summary": summary,
    }


def list_indexed_documents() -> list[dict[str, Any]]:
    """Return one summary entry per indexed document (not per chunk).

    Shared by the documents API route and the agent's `list_docs` tool, so
    both surfaces stay in sync with a single source of truth.

    Returns:
        A list of `{"id": str, "filename": str, "chunks_count": int, "summary": str | None}`.
    """
    collection = get_chroma_collection()
    all_chunks = collection.get(include=["metadatas"])
    metadatas = all_chunks.get("metadatas") or []

    documents: dict[str, dict[str, Any]] = {}
    for metadata in metadatas:
        document_id = metadata.get("document_id")
        if not document_id:
            continue
        if document_id not in documents:
            documents[document_id] = {
                "id": document_id,
                "filename": metadata.get("filename"),
                "chunks_count": 0,
                "summary": metadata.get("summary"),
            }
        documents[document_id]["chunks_count"] += 1

    return list(documents.values())
