"""Document ingestion: extract text, chunk it, embed it, persist to ChromaDB.

Per project policy, `OllamaClient` is the only component allowed to talk to
Ollama over HTTP. Embeddings are therefore generated by calling
`OllamaClient.embed` directly (via a small LangChain-compatible adapter)
instead of using `langchain_ollama.OllamaEmbeddings`, which would open its
own HTTP connection outside that seam and be impossible to mock uniformly.
"""

import uuid
from pathlib import Path
from typing import Any

import chromadb
from chromadb.api.models.Collection import Collection
from docx import Document as DocxDocument
from langchain_text_splitters import RecursiveCharacterTextSplitter
from pypdf import PdfReader

from core.config import settings
from core.ollama_client import OllamaClient
from core.ollama_client import client as default_ollama_client

SUPPORTED_EXTENSIONS = {".pdf", ".docx", ".txt"}
COLLECTION_NAME = "documents"


class UnsupportedFileTypeError(ValueError):
    """Raised when the uploaded file extension is not supported."""


class DocumentExtractionError(ValueError):
    """Raised when text could not be extracted from an otherwise supported file."""


def get_chroma_collection() -> Collection:
    """Return the (persisted) Chroma collection used to store document chunks."""
    chroma_client = chromadb.PersistentClient(path=settings.chroma_persist_dir)
    return chroma_client.get_or_create_collection(name=COLLECTION_NAME)


def _extract_text(file_path: Path, extension: str) -> str:
    """Extract raw text from a document, dispatching on file extension."""
    if extension == ".pdf":
        try:
            reader = PdfReader(str(file_path))
            pages_text = [page.extract_text() or "" for page in reader.pages]
        except Exception as exc:  # noqa: BLE001 - normalize all extraction failures
            raise DocumentExtractionError(
                "Não foi possível extrair texto do documento"
            ) from exc
        text = "\n".join(pages_text).strip()
    elif extension == ".docx":
        try:
            docx_document = DocxDocument(str(file_path))
            text = "\n".join(paragraph.text for paragraph in docx_document.paragraphs).strip()
        except Exception as exc:  # noqa: BLE001 - normalize all extraction failures
            raise DocumentExtractionError(
                "Não foi possível extrair texto do documento"
            ) from exc
    else:  # .txt
        try:
            text = file_path.read_text(encoding="utf-8").strip()
        except (UnicodeDecodeError, OSError) as exc:
            raise DocumentExtractionError(
                "Não foi possível extrair texto do documento"
            ) from exc

    if not text:
        raise DocumentExtractionError("Não foi possível extrair texto do documento")

    return text


async def ingest_document(
    file_path: str,
    filename: str,
    ollama_client: OllamaClient | None = None,
) -> dict[str, Any]:
    """Ingest a single document: extract, chunk, embed, and persist it.

    Args:
        file_path: Path to the file on disk (already saved by the upload route).
        filename: Original filename, used for validation and metadata.
        ollama_client: Optional injected client (defaults to the shared singleton),
            primarily so tests can pass a mock.

    Returns:
        A dict shaped `{id, filename, chunks_count, status}`.

    Raises:
        UnsupportedFileTypeError: If the file extension is not one of
            `SUPPORTED_EXTENSIONS`.
        DocumentExtractionError: If no text could be extracted (corrupted file
            or empty content).
    """
    ollama = ollama_client or default_ollama_client
    path = Path(file_path)
    extension = Path(filename).suffix.lower()

    if extension not in SUPPORTED_EXTENSIONS:
        raise UnsupportedFileTypeError(
            f"Formato de arquivo não suportado: '{extension}'. "
            f"Formatos aceitos: {', '.join(sorted(SUPPORTED_EXTENSIONS))}"
        )

    text = _extract_text(path, extension)

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=settings.rag_chunk_size,
        chunk_overlap=settings.rag_chunk_overlap,
    )
    chunks = splitter.split_text(text)

    document_id = str(uuid.uuid4())
    embeddings = [await ollama.embed(chunk) for chunk in chunks]
    ids = [f"{document_id}-{index}" for index in range(len(chunks))]
    metadatas = [
        {"filename": filename, "chunk_index": index, "document_id": document_id}
        for index in range(len(chunks))
    ]

    collection = get_chroma_collection()
    collection.add(
        ids=ids,
        embeddings=embeddings,
        documents=chunks,
        metadatas=metadatas,
    )

    return {
        "id": document_id,
        "filename": filename,
        "chunks_count": len(chunks),
        "status": "indexed",
    }
